"""phase 4: salary structures and salary rules

Revision ID: 00b8f1f34ec1
Revises: 6734521147cb
Create Date: 2026-09-05 15:27:05.765382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b8f1f34ec1'
down_revision: Union[str, None] = '6734521147cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_structures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_structures_code'), 'salary_structures', ['code'], unique=True)
    op.create_index(op.f('ix_salary_structures_name'), 'salary_structures', ['name'], unique=True)
    op.create_table('salary_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('salary_structure_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('calculation_method', sa.String(length=30), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("calculation_method != 'fixed' OR fixed_amount IS NOT NULL", name='ck_salary_rule_fixed_amount_present'),
    sa.CheckConstraint("calculation_method != 'formula' OR formula IS NOT NULL", name='ck_salary_rule_formula_present'),
    sa.CheckConstraint("calculation_method != 'percentage' OR percentage IS NOT NULL", name='ck_salary_rule_percentage_present'),
    sa.CheckConstraint("calculation_method IN ('fixed', 'percentage', 'formula')", name='ck_salary_rule_calculation_method'),
    sa.CheckConstraint("category IN ('earning', 'allowance', 'deduction', 'contribution')", name='ck_salary_rule_category'),
    sa.CheckConstraint('fixed_amount IS NULL OR fixed_amount >= 0', name='ck_salary_rule_fixed_amount_non_negative'),
    sa.CheckConstraint('percentage IS NULL OR percentage >= 0', name='ck_salary_rule_percentage_non_negative'),
    sa.CheckConstraint('sequence >= 0', name='ck_salary_rule_sequence_non_negative'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salary_structure_id', 'code', name='uq_salary_rule_structure_code'),
    sa.UniqueConstraint('salary_structure_id', 'sequence', name='uq_salary_rule_structure_sequence')
    )
    op.create_index(op.f('ix_salary_rules_code'), 'salary_rules', ['code'], unique=False)
    op.create_index(op.f('ix_salary_rules_salary_structure_id'), 'salary_rules', ['salary_structure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_rules_salary_structure_id'), table_name='salary_rules')
    op.drop_index(op.f('ix_salary_rules_code'), table_name='salary_rules')
    op.drop_table('salary_rules')
    op.drop_index(op.f('ix_salary_structures_name'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_code'), table_name='salary_structures')
    op.drop_table('salary_structures')
    # ### end Alembic commands ###
