"""phase 6: payruns and payslips

Revision ID: 24fffa1742c8
Revises: facd3c2ae029
Create Date: 2026-09-05 16:19:52.481306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24fffa1742c8'
down_revision: Union[str, None] = 'facd3c2ae029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payruns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('salary_structure_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'computed', 'validated', 'paid')", name='ck_payrun_status'),
    sa.CheckConstraint('period_end >= period_start', name='ck_payrun_period_dates'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payruns_reference'), 'payruns', ['reference'], unique=True)
    op.create_index(op.f('ix_payruns_salary_structure_id'), 'payruns', ['salary_structure_id'], unique=False)
    op.create_table('payrun_employees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payrun_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payrun_id', 'employee_id', name='uq_payrun_employee')
    )
    op.create_index(op.f('ix_payrun_employees_employee_id'), 'payrun_employees', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payrun_employees_payrun_id'), 'payrun_employees', ['payrun_id'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payrun_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('salary_structure_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_allowances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_contributions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'computed', 'validated', 'paid')", name='ck_payslip_status'),
    sa.CheckConstraint('period_end >= period_start', name='ck_payslip_period_dates'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payrun_id', 'employee_id', name='uq_payslip_payrun_employee')
    )
    op.create_index(op.f('ix_payslips_contract_id'), 'payslips', ['contract_id'], unique=False)
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_payrun_id'), 'payslips', ['payrun_id'], unique=False)
    op.create_index(op.f('ix_payslips_salary_structure_id'), 'payslips', ['salary_structure_id'], unique=False)
    op.create_table('payslip_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payslip_id', sa.Uuid(), nullable=False),
    sa.Column('salary_rule_id', sa.Uuid(), nullable=True),
    sa.Column('rule_code', sa.String(length=30), nullable=False),
    sa.Column('rule_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('calculation_method', sa.String(length=30), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salary_rule_id'], ['salary_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslip_lines_payslip_id'), 'payslip_lines', ['payslip_id'], unique=False)
    op.create_index(op.f('ix_payslip_lines_salary_rule_id'), 'payslip_lines', ['salary_rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payslip_lines_salary_rule_id'), table_name='payslip_lines')
    op.drop_index(op.f('ix_payslip_lines_payslip_id'), table_name='payslip_lines')
    op.drop_table('payslip_lines')
    op.drop_index(op.f('ix_payslips_salary_structure_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_payrun_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_contract_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_payrun_employees_payrun_id'), table_name='payrun_employees')
    op.drop_index(op.f('ix_payrun_employees_employee_id'), table_name='payrun_employees')
    op.drop_table('payrun_employees')
    op.drop_index(op.f('ix_payruns_salary_structure_id'), table_name='payruns')
    op.drop_index(op.f('ix_payruns_reference'), table_name='payruns')
    op.drop_table('payruns')
    # ### end Alembic commands ###
