"""phase 3: attendance and time off

Revision ID: 6734521147cb
Revises: 7ae8900a4e83
Create Date: 2026-09-05 15:12:52.376127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6734521147cb'
down_revision: Union[str, None] = '7ae8900a4e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_off_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_allocation', sa.Boolean(), nullable=False),
    sa.Column('allow_negative', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_off_types_code'), 'time_off_types', ['code'], unique=True)
    op.create_index(op.f('ix_time_off_types_name'), 'time_off_types', ['name'], unique=True)
    op.create_table('attendance_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_hours', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('check_out IS NULL OR check_out >= check_in', name='ck_attendance_checkout_after_checkin'),
    sa.CheckConstraint('worked_hours IS NULL OR worked_hours >= 0', name='ck_attendance_worked_hours_non_negative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_attendance_employee_date')
    )
    op.create_index(op.f('ix_attendance_records_attendance_date'), 'attendance_records', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_table('time_off_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('time_off_type_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_days', sa.Float(), nullable=False),
    sa.Column('used_days', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('allocated_days >= 0', name='ck_time_off_allocation_allocated_non_negative'),
    sa.CheckConstraint('used_days >= 0', name='ck_time_off_allocation_used_non_negative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_off_type_id'], ['time_off_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_off_allocations_employee_id'), 'time_off_allocations', ['employee_id'], unique=False)
    op.create_index('ix_time_off_allocations_employee_type', 'time_off_allocations', ['employee_id', 'time_off_type_id'], unique=False)
    op.create_index(op.f('ix_time_off_allocations_time_off_type_id'), 'time_off_allocations', ['time_off_type_id'], unique=False)
    op.create_table('time_off_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('time_off_type_id', sa.Uuid(), nullable=False),
    sa.Column('allocation_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('requested_days', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_time_off_request_end_date_after_start_date'),
    sa.CheckConstraint('requested_days > 0', name='ck_time_off_request_requested_days_positive'),
    sa.ForeignKeyConstraint(['allocation_id'], ['time_off_allocations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_off_type_id'], ['time_off_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_off_requests_allocation_id'), 'time_off_requests', ['allocation_id'], unique=False)
    op.create_index('ix_time_off_requests_employee_dates', 'time_off_requests', ['employee_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_time_off_requests_employee_id'), 'time_off_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_time_off_requests_time_off_type_id'), 'time_off_requests', ['time_off_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_off_requests_time_off_type_id'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_employee_id'), table_name='time_off_requests')
    op.drop_index('ix_time_off_requests_employee_dates', table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_allocation_id'), table_name='time_off_requests')
    op.drop_table('time_off_requests')
    op.drop_index(op.f('ix_time_off_allocations_time_off_type_id'), table_name='time_off_allocations')
    op.drop_index('ix_time_off_allocations_employee_type', table_name='time_off_allocations')
    op.drop_index(op.f('ix_time_off_allocations_employee_id'), table_name='time_off_allocations')
    op.drop_table('time_off_allocations')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_time_off_types_name'), table_name='time_off_types')
    op.drop_index(op.f('ix_time_off_types_code'), table_name='time_off_types')
    op.drop_table('time_off_types')
    # ### end Alembic commands ###
