"""phase 2: working schedules and contracts

Revision ID: 7ae8900a4e83
Revises: ac7f712ac3ce
Create Date: 2026-09-05 14:55:42.452104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae8900a4e83'
down_revision: Union[str, None] = 'ac7f712ac3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('working_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('weekly_hours', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_schedules_code'), 'working_schedules', ['code'], unique=True)
    op.create_table('working_schedule_days',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('working_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('is_working_day', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('break_minutes >= 0', name='ck_working_schedule_day_break_minutes'),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_working_schedule_day_weekday'),
    sa.ForeignKeyConstraint(['working_schedule_id'], ['working_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('working_schedule_id', 'weekday', name='uq_working_schedule_day_schedule_weekday')
    )
    op.create_index(op.f('ix_working_schedule_days_working_schedule_id'), 'working_schedule_days', ['working_schedule_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('contract_reference', sa.String(length=50), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('working_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_contract_end_date_after_start_date'),
    sa.CheckConstraint('salary >= 0', name='ck_contract_salary_non_negative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['working_schedule_id'], ['working_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_reference'), 'contracts', ['contract_reference'], unique=True)
    op.create_index(op.f('ix_contracts_employee_id'), 'contracts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_contracts_working_schedule_id'), 'contracts', ['working_schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_working_schedule_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_employee_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_reference'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_working_schedule_days_working_schedule_id'), table_name='working_schedule_days')
    op.drop_table('working_schedule_days')
    op.drop_index(op.f('ix_working_schedules_code'), table_name='working_schedules')
    op.drop_table('working_schedules')
    # ### end Alembic commands ###
